name: Sync Leetcode
on:
  workflow_dispatch:      # Allows you to run it manually
  schedule:
    - cron: '0 21 */2 * *'    # Runs at 21:00 (9PM) UTC every 2 days
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
