name: Sync Leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Official GitHub Action

      - name: Set up Python
        uses: actions/setup-python@v5 # Official GitHub Action
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Sync Script
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python sync_leetcode.py
