name: Sync Leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: Ma6ne/leetcode-sync-bot@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          leetcode_csrf_token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination_folder: 'solutions'
