name: Sync Leetcode
on:
  workflow_dispatch:      # Allows manual trigger
  schedule:
    - cron: '0 21 */2 * *' # Runs at 9PM UTC every 2 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Synchronizer
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in GitHub secret
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
